### ISSUE TITLE
Hide charging popup

### ISSUE THREAD

**Issue by newbiepub** [iZettle/sdk-android#10]
Hello,
# Expected Behavior
Hide Charging popup

I have an branding screen for card tapping but iZettle SDK show a popup which left my branding screen behind. Is there any way that I can hide that ?
# Current Behavior

What is the current behavior?

# Steps to Reproduce

Please provide detailed steps for reproducing the issue.

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version: Android 9+
* SDK version: SDK 3.0.1

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by fabriciovergara** [comment]
I don't quite get the issue. 
Do you want to perform payment without showing a UI?

**Comment by newbiepub** [comment]
@fabriciovergara 
Yes, it is. Could I do it ?

**Comment by fabriciovergara** [comment]
@newbiepub sorry, but we currently have no plans to support such feature.

**Comment by newbiepub** [comment]
@fabriciovergara Yes thank you for your supporting
