### ISSUE TITLE
Unclear documentation regarding ZettleResult class

### ISSUE THREAD

**Issue by Bart-Westenenk** [iZettle/sdk-android#100]
# Problem

I expected better documentation regarding the possible failure reasons and cancellation reasons at [Processing card payment results](https://developer.zettle.com/docs/android-sdk/user-guides/manage-card-payments#processing-card-payment-results). Currently it is unclear if `ZettleResult.failed` could also mean that the balance of the customer is too low (example), or that it only includes errors like "not logged in" or "reader not connected".

**Comment by mfareed-pp** [comment]
The documentation is reflecting the reasons we support at the moment, there are no plans to support this feature in the near future.
