### ISSUE TITLE
FOREGROUND_SERVICE_DATA_SYNC permission requested

### ISSUE THREAD

**Issue by Bart-Westenenk** [iZettle/sdk-android#101]
# Expected Behavior
Submission to play console is as smooth as possible and developers are informed on what manifest permissions are added by the SDK. 

# Current Behavior

The FOREGROUND_SERVICE_DATA_SYNC service permission is requested. Probably for updating a Zettle reader when they are outdated

# How to resolve 
I would like a video, or a way I can make a video of the Zettle SDK upgrading the firmware of my zettle. I currently do not have a Zettle on hand that is out of date enough such that I can make a video.

## Context 
![image](https://github.com/user-attachments/assets/201905b8-a654-45f1-9c95-ec84b0bee3b5)

* Operating Version: Independent of OS version
* SDK version: release-2.24.2

## Failure Logs
NA

**Comment by fparmak** [comment]
Hi @Bart-Westenenk,
I can provide you the video recorded for our [PayPal Zettle: Point of Sale](https://play.google.com/store/apps/details?id=com.izettle.android) app. 

https://github.com/user-attachments/assets/8b1536ee-2d69-4074-b594-cf7acfc072f7

Please let us know if it is still not working for you.

**Comment by Bart-Westenenk** [comment]
Alright, thank you! I will try submitting this one and let you know if we run into problems.
