### ISSUE TITLE
Failed to resolve com.zettle.sdk.feature.cardreader:ui:2.24.2

### ISSUE THREAD

**Issue by ports8865** [iZettle/sdk-android#102]
# Expected Behavior

To be able to build a project and download dependencies

# Current Behavior

Not being able to fetch/install the dependencies in my app

# Steps to Reproduce

I've generated a github token (New personal access token (classic) / Scope:  read:packages Download packages from GitHub Package Registry)

Part of my project build.gradle

`    

repositories {
        google()
        mavenCentral()

        maven {
            url = uri("https://maven.pkg.github.com/iZettle/sdk-android")
            credentials(HttpHeaderCredentials) {
                name = "Authorization"
                value "Bearer gxxxxxxxx"
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }`

Part of my app/build.gradle:

`dependencies {

    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-process:2.8.7'
    implementation 'com.google.code.gson:gson:2.11.0'

    // Core always needed
    implementation 'com.zettle.sdk:core:2.24.2'

    // For Card Reader Payments
    implementation 'com.zettle.sdk.feature.cardreader:ui:2.24.2'
}`

When I'm trying to sync gradle, the sync is successful but I can see the warning for the two zettle related dependencies:

```
Failed to resolve: com.zettle.sdk:core:2.24.2  (EDITED to correct the right module)
Failed to resolve: com.zettle.sdk.feature.cardreader:ui:2.24.2
```

Please advise. Thank you.

**Comment by momoamennn** [comment]
Hello @ports8865, thank you for reaching out.

Just to confirm, you are able to resolve the core dependency `com.zettle.sdk:core:2.24.2`, but you are unable to resolve the reader dependency `com.zettle.sdk.feature.cardreader:ui:2.24.2`.

If this is the case, could you please double check that you did not encounter any other errors? It's possible that a connection timeout or another issue occurred while fetching the reader dependency.

**Comment by momoamennn** [comment]
If you are still experiencing the same issue, please confirm the outcome when using the older version, 2.16.2, for both the core and reader dependencies.

**Comment by ports8865** [comment]
@momoamennn Thanks for your response. It's actually for both dependencies: core and cardreader (apologies, my copy and paste was incorrect in the original post. Edited now).

I've tried changing the version to 2.16.2 but it cannot resolve either of the dependencies either.

There's no other error. I wonder what I'm getting wrong. This is the screen when I click on the Download Info.

<img width="1660" alt="image" src="https://github.com/user-attachments/assets/724e83f2-c08f-40f9-b6cd-e7958d1b99a2" />

**Comment by ports8865** [comment]
Apologies. I've had my build.gradle structure misconfigured. All good.
