### ISSUE TITLE
Can iZettle reader and this SDK work with Bluetooth 3.0 (non LE) Android devices? 

### ISSUE THREAD

**Issue by derrickrc** [iZettle/sdk-android#14]
Is there an iZettle reader that does not require Bluetooth LE (for older Android devices)? And if so, does this SDK support those readers? Thank you.

**Comment by fabriciovergara** [comment]
There is a iZettle Reader V1 (with blue button) which uses classic BT. 
But be aware that this SDK supports Android 5 or above, it works with 4.4 but LE is a bit flacky.

**Comment by derrickrc** [comment]
Awesome, thank you Fabricio.

**Comment by derrickrc** [comment]
Sorry @fabriciovergara, and just to clarify if I have an Android 5 device that does not have LE (only classic), can I still use this SDK?

**Comment by fabriciovergara** [comment]
Yes, you will be able to use the SDK, but you will need a card reader that uses classic BT (with blue button), which depending where are you placed it can have limited stock. Please verify with your local iZettle support/sales line beforehand.
