### ISSUE TITLE
json response - code_verifier error

### ISSUE THREAD

**Issue by real-iot** [iZettle/sdk-android#16]
# Expected Behaviour

I am having problems with my PHP for the Oauth2 authentication (Access token fetch)

# Current Behaviour

I can get the “code” + “state” in my PHP script – but when I try to fetch the access token from “https://oauth.izettle.com/token” I am getting an error message :

**_“json={"error":"invalid_request","error_description":"code_verifier cannot be empty"}”_**

# Steps to Reproduce

I have all the code compiling and building in android studio – that is all good - no modifications to the main code - values are setup in iZettleSDK.gradle (githubAccessToken/clientId/redirectUrlScheme/redirectUrlHost)

## Context 
* Operating Version: Android 10 on moto g8
* SDK version: release-1.8.9

## Failure Logs

**_“json={"error":"invalid_request","error_description":"code_verifier cannot be empty"}”_**

**Comment by bobzettle** [comment]
Hi, apologies for not hearing from us. Have you managed to sort this out?
The issue will now be closed, but feel free to add a comment if you still need help and we'll get back to you shortly.
