### ISSUE TITLE
Send Payment Links - Android SDK

### ISSUE THREAD

**Issue by xeb10154** [iZettle/sdk-android#18]
This might not be the best place to post this as it's not an issue as such. I would like to include the capability to send Payment Links from a bespoke app for a private client. My client is currently using the IZettle app, but they are exploring their own bespoke solutions catered for their use case integrated with the IZettle card reader and also have the capability to send Payment Links from this bespoke app for their business. Is this currently possible with the SDK? If not, then is there any plans to add this in the future?

Thanks,

xeb

**Comment by dmilovanovi** [comment]
Hi!

Sincere apologies for the delay in getting back to you! The Payment link is a feature of the Zettle GO app and as such, we do not have it included in the SDK. This sounds like an interesting feature-request, so I will be sure to provide feedback to the team for future considerations.

Regards,
