### ISSUE TITLE
Missing Enforced User Account feature.

### ISSUE THREAD

**Issue by newbiepub** [iZettle/sdk-android#20]
# Expected Behavior

I was building a payment app on both Android and iOS. I wanted to restrict the usage of the SDK to a certain iZettle account as I could do it on iOS.

# Current Behavior

On iOS I saw that we have the feature Enforced User Account but Android.

* Operating Version: 9.0
* SDK version: 1.8.9

**Comment by dmilovanovi** [comment]
Hi! 

Sincere apologies for the delay in getting back to you!
Unfortunately, the enforcedAccount feature has not yet been developed for the Android version of the SDK. 
I’ll be sure to provide feedback to the team for future considerations. 

Regards
