### ISSUE TITLE
transparent or auto login

### ISSUE THREAD

**Issue by jonarderic74** [iZettle/sdk-android#25]
How to login in transparent or auto login a app. 
I need my app log without tell the account.
Waiting for a onlisten or handler to do a UI myself.
Thank you

**Comment by bobzettle** [comment]
We do not currently support other logins than the built in OAuth flow at the moment. 
But the feature of handling the OAuth process outside the SDK and login with an already acquired access token is in our plans but I there's no estimate on when it will be published.
