### ISSUE TITLE
Transactionreference info

### ISSUE THREAD

**Issue by jonarderic74** [iZettle/sdk-android#31]
How send a name of product or use a product in the catalog with Transactionreference ?

**Comment by bobzettle** [comment]
Hi, this is described in the [readme](https://github.com/iZettle/sdk-android#step-5-starting-payment). 

> Using the put method you can add whatever you want to this object, but keep in mind that the total data size (including key names) in this object can't be bigger than 4 kilobytes. You will get this reference back with transaction data and can always request it back from our servers.

So to put a product name in there you would do something similar to this.
```
val productNameKey = "arbitary string of your choice"

val internalTraceId = UUID.randomUUID().toString()
val reference = TransactionReference.Builder(internalTraceId)
    .put(productNameKey, productName)
    .build()
```
