### ISSUE TITLE
Authentication with an Assertion Grant

### ISSUE THREAD

**Issue by christhwaites** [iZettle/sdk-android#33]
I am attempting a private integration of the android zettle sdk, and would prefer to use the Assertion Grant rather than the authorization code grant. This is because I do not wish my users to have to type in an iZettle username and password, as well as their authentication with my own ordanisation. I'm hoping to authenticate the user myself, and then generate and pass on the zettle access token myself.

Is this possible with the android sdk? I cannot see any methods on the User object where  I might use an access token to authenticate. 

Or am I missing something fundamental? I'm new to OAuth and might have completely missed the point...

Thanks,
    Chris

**Comment by javiersanchezra** [comment]
Tried this sceneraio before,  it seems not posible .

**Comment by bobzettle** [comment]
Hi, to authenticate through an access token is not yet available in the Android SDK. It's in our backlog and I will push for it's prioritizations. 

Please follow the releases [here](https://github.com/iZettle/sdk-android/releases) to see when it's available.

**Comment by dahLucky** [comment]
Hi @bobzettle , we are looking into a similar use-case as described by @christhwaites. Is there any progress on issue? 
Thank you
