### ISSUE TITLE
Connection problem using two devices and one zettle terminal

### ISSUE THREAD

**Issue by To0m** [iZettle/sdk-android#37]
# Expected Behavior

I would like to use a Zettle terminal with multiple devices. I would like to be able to process a payment on both devices one after the other.
Is it possible to use a Zettle terminal with multiple devices that have the SDK integrated?

# Current Behavior

When I complete a payment with the first device and then want to start a payment with a second device, I can't connect to the terminal. Only when I completely close my app on the first device can I establish a connection with the second device. It seems that the Bluetooth connection does not end automatically.

Does anyone have experience dealing with this?

# Steps to Reproduce

Use an App with integrated SDK on two devices with one zettle terminal. Complete an payment on device 1 and then try to start an payment on device 2.

## Context 

Multiple point of sales running the same POS-App with the integrated zettle sdk and one zettle card terminal.

* Operating Version: Android 12 (same issue on iOS)
* SDK version: 1.14.15

**Comment by fabriciovergara** [comment]
Hi,

Unfortunately the reader don't have such capability. When reader connect to device it will "lock" to this device and block any external connection attempt as long the current connection exists.

**Comment by To0m** [comment]
Okay, thanks for the feedback.
