### ISSUE TITLE
Working with gift cards

### ISSUE THREAD

**Issue by DowsingUK** [iZettle/sdk-android#43]
# Expected Behavior
Working with gift cards
# Current Behavior

What is the current behavior?
No documentation found for working with gift cards

# Steps to Reproduce
No documentation found

## Context 
Custom Android and iOS app

* Operating Version:
* SDK version: Last

## Failure Logs
No documentation found

**Comment by dmilovanovi** [comment]
Hi @DowsingUK 

Apologies for the delay in getting back to you!

Working with gift cards is a feature of the Zettle POS and as such, it is not supported by the SDK - which is why we don't have that documented.

I will make sure to provide feedback to my team for future considerations!

Regards
