### ISSUE TITLE
With Cordova plugin android

### ISSUE THREAD

**Issue by stonehorsecd** [iZettle/sdk-android#46]
### Expected Behavior
fix these two issues.

### Current Behavior

I wrote a  custom cordova plugin with android , I found two issues. 
First when charge process with enable login , on the login page, I can **click login button multiple times**, that will caused the page to repeat.
Second issue is in charge process with enable login, after I login successfully, back to OAuthActivity, **the login page continue to show some time** , about 1 - 8 seconds, this cause user could click login in button again. But if user ignore this , this page will disappear and go to next step after wait.  To this callback OAuthActivity, I expect add a loading display or hide the login button , for it's in process.

### Steps to Reproduce
Write a cordova plugin use sample java sdk, install and run.

**Comment by bobzettle** [comment]
Hi and thank you for your feedback. 
I will bring this request to our planning to see if we can prioritise to work on it.

**Comment by davidzettle** [comment]
Hello and sorry for the waiting time to update this thread. This issue was solved in Q2 this year, so I will go ahead and close this thread. 

Feel free to reopen if this has persisted in any form.

Regards,
