### ISSUE TITLE
oath and automatic login

### ISSUE THREAD

**Issue by hennaboy** [iZettle/sdk-android#53]
I thought the whole idea behind oath was that it would save credentials to provide automatic login procedures. 

In my app, I am required to enter an email and password on every launch. This is not a big problem just seems to me that there should be a seamless way of doing an automated login procedure unless I have missed something or something in my integration is not configured correctly?

**Comment by bobzettle** [comment]
Hi @hennaboy, 

Yes you are right to assume that the authentication should be refreshed by the SDK as long as the refresh-tokens are valid and authorized using the PKCE method. 

How are you authenticating today? With the[ provided UI](https://github.com/iZettle/sdk-android#initiate-authorization-with-provided-ui) or with [token](https://github.com/iZettle/sdk-android#initiate-authorization-with-token)?

**Comment by hennaboy** [comment]
> Hi @hennaboy,
> 
> Yes you are right to assume that the authentication should be refreshed by the SDK as long as the refresh-tokens are valid and authorized using the PKCE method.
> 
> How are you authenticating today? With the[ provided UI](https://github.com/iZettle/sdk-android#initiate-authorization-with-provided-ui) or with [token](https://github.com/iZettle/sdk-android#initiate-authorization-with-token)?

I guess its the provided UI as it goes to login.zettle.com for email and password input which then returns back to the app.

On android 10+ this opens in chrome browser so I end up with numerous amount of chrome tabs.

I will ask my developer to look at the token.

**Comment by bobzettle** [comment]
Let me know if there's still an issue and provide as detailed information as possible.

**Comment by bobzettle** [comment]
Hi, since we haven't heard back during the last month we will be closing this issue now. 
Feel free to reopen with new comments if needed.

**Comment by crashfiredeep** [comment]
@bobzettle How can we authorize app with PKCE? Currently login can be only done in browser, and each time it is asking for to login. I did not found to store data even after login successfully in onActivityResult() method. can you help to find please.
