### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by vivekvardhanadepu** [iZettle/sdk-android#57]
I am getting this error after following the setup steps
```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.izettle.payments:android-sdk-ui:1.24.0.
     Required by:
         project :app
      > No cached version of com.izettle.payments:android-sdk-ui:1.24.0 available for offline mode.
```

# Steps to Reproduce
https://developer.zettle.com/docs/android-sdk/installation-and-configuration

## Context 
```
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
```
SDK version: 1.25.6

**Comment by bobzettle** [comment]
Hi. it seems like you are working in offline mode. Try if it helps to be online and fetch the dependencies. 

Also, I know there's an older version in the documentation, try to use the latest version: `com.izettle.payments:android-sdk-ui:1.25.6` in the gradle file as well.

**Comment by vivekvardhanadepu** [comment]
> Hi. it seems like you are working in offline mode. Try if it helps to be online and fetch the dependencies.
> 
> Also, I know there's an older version in the documentation, try to use the latest version: `com.izettle.payments:android-sdk-ui:1.25.6` in the gradle file as well.

online mode worked. Thanks!!
