### ISSUE TITLE
supportsRtl 

### ISSUE THREAD

**Issue by YiffyToys** [iZettle/sdk-android#65]
# Expected Behavior

Right To Left language support support 

# Current Behavior
```
Attribute application@supportsRtl value=(true) from AndroidManifest.xml:16:13-39
	is also present at [com.izettle.android.qrc:paypal-qrc-sdk:1.30.1] AndroidManifest.xml:9:18-45 value=(false).
```

# Steps to Reproduce

buid a new app with RTL support

**Comment by davidzettle** [comment]
Hello, 

Thank you for flagging this. At the time being we are not active in any markets where LTR is an option, and we are not looking into adding this option in the near future either.

We will remove this line of code in our next release, thank you for your feedback.

Regards,

**Comment by YiffyToys** [comment]
This is not about the market = merchant language but about the CUSTOMER language.
Huge difference.
