### ISSUE TITLE
How to add user login?

### ISSUE THREAD

**Issue by Catzoy** [iZettle/sdk-android#7]
In step 2 of "Getting Started" our app must add a callback activity for user OAuth login with some "redirect URL", yet it is unclear what redirect URL must do and who provides such URL. 
Please explain how to add user authorization to the app.

**Comment by fabriciovergara** [comment]
Hi @Catzoy

Sorry for the lack if details, there is still a work in progress regarding the integration process and documentation.

In the https://developer.izettle.com/ after you create a Payments Android SDK credential you will be prompted to add the redirect URI and after we a user finish an authentication in the app (which happen in a browser) we still redirect to this URI and the sdk will handle the result. 

We suggest to not use https since it's really specific for iZettle login for your app and we would like to not have deep link conflict with other apps, in the same way when you share a photo and you are prompted to choose which app will handle it. 

If you choose this redirect URI:

<img width="399" alt="Screenshot 2020-07-13 at 15 29 33" src="https://user-images.githubusercontent.com/5910915/87310693-99e78880-c51e-11ea-82d0-d56b4f8041d6.png">
 
Then in our sample you must fill the iZettleSDK.gradle with this:

<img width="357" alt="Screenshot 2020-07-13 at 15 39 23" src="https://user-images.githubusercontent.com/5910915/87311082-15493a00-c51f-11ea-9a97-61e8b1fa3cfd.png">

Please, let us know if you have any problem.

**Comment by Catzoy** [comment]
Hi @fabriciovergara 

Thank you for quick response! 

Issue was that we didn't add any OAuth Redirect URI in the https://developer.izettle.com/ for our app and that's why SDK always returned "redirect_url contains not allowed URI" for anything we tried.

Closing issue as resolved.

**Comment by remitettiravou** [comment]
Hi,

@fabriciovergara you said the SDK "will handle the result" when redirected in redirect URL. 
In my app, after login in the browser, I see the access_token (displayed from my redirect_uri), and that's all, nothing else is happening. How do we return to the application with the access_token taken into account ?

Thanks

Rémi

**Comment by fabriciovergara** [comment]
@remitettiravou 

After the login, the browser will be redirect to the deep-link registered in your app manifest:

```xml
<activity 
    android:name="com.izettle.android.auth.OAuthActivity" 
    android:launchMode="singleTask"
    android:taskAffinity="@string/oauth_activity_task_affinity"> 
    <intent-filter> 

        <!-- Deep link data -->
        <data 
            android:host="izettlelogin"  
            android:scheme="izettlesample />
       

       <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
    </intent-filter>
</activity>
```

Please, check if the values are correct and the same as declared in the developer portal.

**Comment by remitettiravou** [comment]
I used to have https scheme. Now with "app" scheme and my Activity for host, it is working. Thanks.

**Comment by Olmectron** [comment]
I'm getting the message: 

**Invalid protocol, can not start with "izettle" or be one of http:// or file://.**

Ehen trying to put izettlesample://izettlelogin in the OAuth Redirect URIs list.

Has the correct redirect URI changed by now?

**Comment by atsneves** [comment]
@Olmectron please not use in the scheme the words http or izettle

**Comment by crashfiredeep** [comment]
> Hi @Catzoy
> 
> Sorry for the lack if details, there is still a work in progress regarding the integration process and documentation.
> 
> In the https://developer.izettle.com/ after you create a Payments Android SDK credential you will be prompted to add the redirect URI. In the app, after user finish an authentication (which happen in a browser) we still redirect to this URI and the sdk will handle the result.
> 
> We suggest to not use https since it's really specific for iZettle login for your app and we would like to not have deep link conflict with other apps, in the same way when you share a photo and you are prompted to choose which app will handle it.
> 
> If you choose this redirect URI:
> 
> <img alt="Screenshot 2020-07-13 at 15 29 33" width="399" src="https://user-images.githubusercontent.com/5910915/87310693-99e78880-c51e-11ea-82d0-d56b4f8041d6.png">
> 
> Then in our sample you must fill the iZettleSDK.gradle with this:
> 
> <img alt="Screenshot 2020-07-13 at 15 39 23" width="357" src="https://user-images.githubusercontent.com/5910915/87311082-15493a00-c51f-11ea-9a97-61e8b1fa3cfd.png">
> 
> Please, let us know if you have any problem.

I have also followed same and login is working redirecting to app but never able to see access token and refresh token in onActivityResult().  but what about access token as mentioned in documentation??



But i can see the log like 
2023-01-03 11:42:51.144 25633-25700/com.pospal.pospal I/TokenRepositoryImpl: [{userId=3f329550-70fb-11e5-a847-bda5b59ed83f, tokens=OAuthTokens(accessToken=ey***tg, refreshToken=IZ***89, expirationDate=Tue Jan 03 13:42:50 GMT+05:30 2023, scopes=[READ:PAYMENT, READ:USERINFO, WRITE:PAYMENT])}]
        at com.izettle.android.auth.log.StackTraceKt.withStackTrace(SourceFile:1)
        at com.izettle.android.auth.TokenRepositoryImpl$applyStoreTokensToTransaction$1.invoke(SourceFile:3)
        at com.izettle.android.auth.TokenRepositoryImpl$applyStoreTokensToTransaction$1.invoke(SourceFile:1)
        at com.izettle.android.auth.storage.Transaction.commit(SourceFile:27)
        at com.izettle.android.auth.tasks.OAuthLoginTask.finalizeTask(SourceFile:10)
        at com.izettle.android.auth.tasks.OAuthAuthTask$resume$1.invoke(SourceFile:15)
        at com.izettle.android.auth.tasks.OAuthAuthTask$resume$1.invoke(SourceFile:1)
        at com.izettle.android.auth.executor.ExecutorImpl.schedule$lambda-3(SourceFile:2)
        at com.izettle.android.auth.executor.ExecutorImpl.$r8$lambda$ApSXqycmJTVshYvryZVW9t0bXko(Unknown Source:0)
        at com.izettle.android.auth.executor.ExecutorImpl$$ExternalSyntheticLambda0.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2023-01-03 11:42:51.216 25633-25633/com.pospal.pospal I/XDR::VRT: sc is not valid!

**Comment by CheZhongSdk** [comment]
@crashfiredeep Not sure I understand your question correctly. But you don't get the `AccessToken` or `RefreshToken` in the `onActivityResult()`. Instead, you should observe the authentication state. Please see [this](https://developer.zettle.com/docs/android-sdk/initialization#observe-authorisation-state).

**Comment by crashfiredeep** [comment]
> @crashfiredeep Not sure I understand your question correctly. But you don't get the `AccessToken` or `RefreshToken` in the `onActivityResult()`. Instead, you should observe the authentication state. Please see [this](https://developer.zettle.com/docs/android-sdk/initialization#observe-authorisation-state).
> 
> Here is the example code in Example project. (https://github.com/iZettle/sdk-android/blob/master/Examples/Example-Kotlin/app/src/main/java/com/izettle/payments/android/kotlin_example/MainActivity.kt#L33)

that is already implemented but if logged in states of login is also coming false, and what if I need to access payment flow using token. in these methods there is no way to get token and refresh token. My app is need to login every time for payment, so I want to store the token and process further based on this token, so that user only need to login once.

**Comment by bobzettle** [comment]
Hi @crashfiredeep, the SDK doesn't expose the tokens and we have no plan of doing so. 
Today there are two ways of authenticating the SDK. 
- The SDK handles everything, you just tell it to log in. 
- You handle authentication and provide a refresh token that the SDK can use to fetch access tokens when needed. When doing a refund a UI will be triggered to verify the credentials. 

Both of the above methods will keep the user logged in as long as the tokens are valid. So if you don't explicitly log out the user you should not be prompted to log in on every payment. The tokens are valid for quite some time. 

As a side note.
We are also working on a third way where the integrator is in full control over the tokens and the SDK will only ask for tokens when needed leaving the integrator in full control. But we don't have a release date for this yet.

**Comment by hennaboy** [comment]
I am attempting to implement this but I am still stuck with Parameter redirect_url contains an URI that is not allowed

ext.iZettleSDK.redirectUrlScheme = "com.pospal.epos"
ext.iZettleSDK.redirectUrlHost = "oauth"

and the redirect url in the developer OAuth Redirect URIs is set to the same com.pospal.epos://oauth
