### ISSUE TITLE
Feature: Tap to Pay 

### ISSUE THREAD

**Issue by dahLucky** [iZettle/sdk-android#76]
Dear Zettle-Team, 
I wondered if there are any plans to add [Tap to Pay](https://www.zettle.com/gb/help/articles/2983722-tap-to-pay) to this SDK.

Thank you, 
Lu

**Comment by rafa-izettle** [comment]
Hi @dahLucky, 
We are currently investigating the effort of this feature on the sdk.
Thank you for reaching out and showing interest in tap to pay.
