### ISSUE TITLE
Incompatible with the most recent React Native version

### ISSUE THREAD

**Issue by kristdevmaster** [iZettle/sdk-android#77]
This SDK helps many POS apps. But I could find out one issue with this sdk. 

# Expected Behavior

You should be able to integrate this apk without an issue.

# Current Behavior

This sdk prevents the metro server of the React Native 0.71 version somehow. It shows following error screen. 

![iZettle-Error](https://user-images.githubusercontent.com/69649913/214590824-eeead5b1-1071-4007-bc45-aed735b84dfc.png)

# Steps to Reproduce

- Create a fresh 0.71 version React Native project.
- Run android ```yarn android```. It has no issue and show the fresh RN project screen with the metro server.
- Add this sdk into the android.
    In the project's build.gradle, add:
    
    allprojects {

     repositories {
        maven {
            url = uri("https://maven.pkg.github.com/iZettle/sdk-android")
            credentials(HttpHeaderCredentials) {
                name "Authorization"
                value "Bearer ${iZettleSDK.githubAccessToken}"
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
        google()
        mavenCentral()
     }
   }
 

- And in the app's build.gradle, add following line.

 ```implementation 'com.izettle.payments:android-sdk-ui:1.36.1'```

- Run android again - ```yarn android```

- It opens the metro server. But metro server doesn't connect.

## Context 

* Operating Version: MacOS 
* SDK version: latest Github version - 1.36.1
* React Native version - 0.71.1
* React Native is created with ```npx react-native init AwesomeProject```

Please let me know how to debug this sdk integration with React Native. Or please try on your side and let me know how to fix this issue. Thanks.

**Comment by davidzettle** [comment]
Hello and thank you for reaching out.

Unfortunately, we don't support react native currently so we are unable to guarantee its correct functioning. 

We would recommend to update to latest available gradle version  as a potential troubleshooting step but we still don't recommend the use of react to avoid unexpected errors.

Best regards,
