### ISSUE TITLE
Really slow processing time

### ISSUE THREAD

**Issue by hennaboy** [iZettle/sdk-android#78]
# Expected Behavior

Previous versions of the SDK were much quicker than this with under 5 seconds to the approval/decline response

# Current Behavior

8-10 seconds to return approval.

# Steps to Reproduce

Contactless payments are taking a long time to process as stated above. It will take anywhere between 8 - 10 seconds to get a response on the card reader. 

## Context 

Android 10 tablets same situation observed on 3 different tablets all different models and manufacturers.

* Operating Version: Android 10
* SDK version: 1.36.1

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by davidzettle** [comment]
Hello and thank you for reaching out.

We have not been able to reproduce this issue in our end.  To further troubleshoot we may need more additional information specific to your account. Please raise a ticket here: [Developer Support - SDK payments and refunds](https://ext-izettle.atlassian.net/servicedesk/customer/portal/3/group/4/create/23)

Please include:
- If this error happens only on tablets or also devices.
- If the location services on these devices are set to "high accuracy" (This could be causing latency if turned off).
- Fill in all the details in the form, including org uuid so we can look into your account for any potential additional clues.
- Add as much information you think may be relevant for us.

Thank you.

**Comment by hennaboy** [comment]
Just in case others coming looking with the same issue it has been improved by turning on Google Location Accuracy.
