### ISSUE TITLE
development mode

### ISSUE THREAD

**Issue by AlfredoRguezc** [iZettle/sdk-android#86]
i dont know how add this part of code and in wich file ? i want to test the paycard pyment

val config = config(applicationContext) {
    isDevMode = true
    ...
)
ZettleSDK.configure(config)

**Comment by CheZhongSdk** [comment]
Hi @AlfredoRguezc, Thanks for reaching out! You can set `isDevMode` when you initialise the Zettle SDK. Please see [this](https://github.com/iZettle/sdk-android/blob/master/Examples/Example-Kotlin/app/src/main/java/com/zettle/payments/android/kotlin_example/MainApplication.kt#L31) example in the sample app. Also, thanks for your comment, we will improve our documentation to make it more clear there too.
