### ISSUE TITLE
Buttons are not displayed correctly

### ISSUE THREAD

**Issue by ShopperPOS** [iZettle/sdk-android#9]
Hello IZettle Team we discovered that the buttons in the SDK views are not displaying correctly. 

The tests were performed on a tablet samsung galaxy Tab A 8 '2019 with Android version 9.0 

We attach screenshots of how the view is currently displayed. As you can see, no button with color is shown to the user.

![Screenshot_20200924-192123_Shopper Deli](https://user-images.githubusercontent.com/70666979/94213427-530dfb80-fe9c-11ea-9ab6-c252ae2fffb3.jpg)
![Screenshot_20200924-191931_Shopper Deli](https://user-images.githubusercontent.com/70666979/94213431-5608ec00-fe9c-11ea-9e67-827c4f33cb38.jpg)
![Screenshot_20200924-192357_Shopper Deli](https://user-images.githubusercontent.com/70666979/94213432-56a18280-fe9c-11ea-9bc4-256e3c04a320.jpg)
![Screenshot_20200924-191854_Shopper Deli](https://user-images.githubusercontent.com/70666979/94213434-56a18280-fe9c-11ea-982d-b9682f926a0e.jpg)

**Comment by fabriciovergara** [comment]
@ShopperPOS  Should be fixed on 1.8.8
