### ISSUE TITLE
Feature request: URL scheme triggering of card readers

### ISSUE THREAD

**Issue by Bart-Westenenk** [iZettle/sdk-android#91]
# Expected Behavior

There is a way for web applications (SPA) to trigger payments in the Zettle application. This works the same on all operating systems.

# Current Behavior

No way currently exists to call both android and IOS from an SPA or web application. SumUp has 1 URL scheme that works for both OSes.

## Context 

We don’t have the capacity to make both an IOS app, Android app and a website for managing our e-commerce application where payments are taken using your Zettle card readers.

* Operating Version: IOS and Android
* SDK version: Irrelevant

**Comment by ppeelen** [comment]
Hi Bart!

Again, thank you for reaching out. 
I have answered your feature request in [this thread](https://github.com/iZettle/sdk-ios/issues/446#issuecomment-1873336564) as well.

**Comment by ppeelen** [comment]
Closing this issue, with reference to the comment made [here](https://github.com/iZettle/sdk-ios/issues/446#issuecomment-1873823066).
