### ISSUE TITLE
403 Forbidden upon successful authentication

### ISSUE THREAD

**Issue by fobos531** [iZettle/sdk-android#92]
# Expected Behavior

After successful authentication, I should be able to properly exit the Webview back into my app.

# Current Behavior

I'm getting a 403 Forbidden upon successful authentication via the Managed authentication flow. See picture: 

![CleanShot 2024-01-03 at 23 23 44@2x](https://github.com/iZettle/sdk-android/assets/19533289/1fbb7bb8-d6cc-48dc-8dff-fe7b93928f65)

# Steps to Reproduce

Use the Managed authentication flow.
Login with Zettle account.
Observe that a 403 error occurs.

## Context 

* Operating Version: API 34
* SDK version: 2.6.7

This is the OAuth redirect URL that I set in the dashboard

![CleanShot 2024-01-03 at 23 26 09@2x](https://github.com/iZettle/sdk-android/assets/19533289/8ef00661-ae96-49b9-ab82-be0f18946088)

This is how I initialize the SDK.

![CleanShot 2024-01-03 at 23 26 59@2x](https://github.com/iZettle/sdk-android/assets/19533289/26dd51a4-0061-4ef2-9c3c-6e3b1ff08bb9)

This is how I start the login flow:

`ZettleSDK.instance?.login(currentActivity)`

I can then successfully login, but at the point where I should get back into my app, I just get a 403 in the webview.

In AndroidManifest I also made sure to include the relevant schemes:

![CleanShot 2024-01-03 at 23 28 25@2x](https://github.com/iZettle/sdk-android/assets/19533289/31f84631-d27d-4eb5-8c4b-1fc10b01c6f0)

Is there anything else that I'm missing?

## Failure Logs

I don't see any failures in ADB logs.

**Comment by fobos531** [comment]
Interestingly enough, I noticed that if I try to use the client ID of my iOS application - then I don't get a 403 and it seems like I logged in, but it doesn't **actually** log me in.

**Comment by CheZhongSdk** [comment]
Hi Jakov @fobos531 , Thank you for reaching out!

I don't see the full picture of your manifest file, but seems `OAuthActivity` is missing there. Please try to follow this [document](https://developer.zettle.com/docs/android-sdk/installation-and-configuration#authentication) to add the OAuthActivity to your manifest.
Also, regarding the client ID issue. You can verify it by using our [Example app](https://github.com/iZettle/sdk-android/tree/master/Examples/Example-Kotlin), simply fill in the values in [zettleSDK.gradle](https://github.com/iZettle/sdk-android/blob/master/Examples/Example-Kotlin/zettleSDK.gradle) file. Then run the app to test your client ID.

**Comment by fobos531** [comment]
Hello @CheZhongSdk 

Thanks for getting back. I added this activity like this:

```
 <activity
    android:exported="true"
    android:name="com.izettle.android.auth.OAuthActivity"
    android:launchMode="singleTask"
    android:taskAffinity="@string/oauth_activity_task_affinity">
    <intent-filter>
        <data android:host="oauth" android:scheme="zettleuxapptest" />
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
    </intent-filter>
</activity>
```

but I'm still getting the exact same error. Please note the android:host and android:scheme. In the developer dashboard, I declared the OAuth Redirect URI as `zettleuxapptest://oauth`. I also tested this on the Example App and I filled it out like this:
![CleanShot 2024-01-04 at 14 19 53@2x](https://github.com/iZettle/sdk-android/assets/19533289/b5839646-85f3-4cd0-84e7-b08459294e86)


But I am still getting the same error even in the example app.  Again, there are no errors in logcat. Is there anything else I could try?

**Comment by fobos531** [comment]
> Hi Jakov, could you check the `App package` you registered in the Develop [Dashboard](https://developer.zettle.com/dashboard) match the app you are developing for? They should be same.
> 
> If it's still not working for you. I suggest you contact our Support Service Desk [Developer Support - SDK payments and refunds](https://ext-izettle.atlassian.net/servicedesk/customer/portal/3/group/4/create/23) to provide your client ID, then we could verify it here.

Hello Che, 

Yes, I confirmed that it is the exact same. I contacted the Support Service Desk and I am awaiting a resolution. Thanks!

Also, is there an ability to delete the app from the dashboard? I have a few of them that I only used for testing and would like to delete them since I no longer need them.

**Comment by fobos531** [comment]
Hello @CheZhongSdk 

I did some more digging and had success after all. It looks like it was a misconfiguration on my end regarding the oauth redirect URI. If the issue reappears I will reopen it, but I'll close it for now.

Thank you for your assistance!
