### ISSUE TITLE
release-2.11.1 has references to missing com.airbnb.lottie.* classes

### ISSUE THREAD

**Issue by planetcoops** [iZettle/sdk-android#93]
# Expected Behavior

Please describe the behavior you are expecting.

Compiles without the following R8 errors:

```
Missing class com.airbnb.lottie.LottieAnimationView (referenced from: com.airbnb.lottie.LottieAnimationView com.izettle.ui.components.movie.OttoMovie.lottieAnimationView and 7 other contexts)
Missing class com.airbnb.lottie.LottieProperty (referenced from: void com.izettle.ui.components.movie.OttoMovie.setMovieAnimationStyle(com.izettle.ui.components.illustration.OttoIllustrationStyles))
Missing class com.airbnb.lottie.model.KeyPath (referenced from: com.airbnb.lottie.model.KeyPath com.izettle.ui.components.movie.OttoMovieKeyPaths.keyPath and 4 other contexts)
Missing class com.airbnb.lottie.value.LottieFrameInfo (referenced from: java.lang.Integer com.izettle.ui.components.movie.OttoMovie.setMovieAnimationStyle$lambda-8$lambda-5(com.izettle.ui.components.movie.OttoMovie, int, com.airbnb.lottie.value.LottieFrameInfo) and 2 other contexts)
Missing class com.airbnb.lottie.value.SimpleLottieValueCallback (referenced from: void com.izettle.ui.components.movie.OttoMovie.setMovieAnimationStyle(com.izettle.ui.components.illustration.OttoIllustrationStyles))
```

# Current Behavior

What is the current behavior?

More of a heads up than anything else that the R8 compilation fails with the following missing class errors:

```
Missing class com.airbnb.lottie.LottieAnimationView (referenced from: com.airbnb.lottie.LottieAnimationView com.izettle.ui.components.movie.OttoMovie.lottieAnimationView and 7 other contexts)
Missing class com.airbnb.lottie.LottieProperty (referenced from: void com.izettle.ui.components.movie.OttoMovie.setMovieAnimationStyle(com.izettle.ui.components.illustration.OttoIllustrationStyles))
Missing class com.airbnb.lottie.model.KeyPath (referenced from: com.airbnb.lottie.model.KeyPath com.izettle.ui.components.movie.OttoMovieKeyPaths.keyPath and 4 other contexts)
Missing class com.airbnb.lottie.value.LottieFrameInfo (referenced from: java.lang.Integer com.izettle.ui.components.movie.OttoMovie.setMovieAnimationStyle$lambda-8$lambda-5(com.izettle.ui.components.movie.OttoMovie, int, com.airbnb.lottie.value.LottieFrameInfo) and 2 other contexts)
Missing class com.airbnb.lottie.value.SimpleLottieValueCallback (referenced from: void com.izettle.ui.components.movie.OttoMovie.setMovieAnimationStyle(com.izettle.ui.components.illustration.OttoIllustrationStyles))
```

Can be suppressed by adding the following lines to proguard-rules.txt

```
-dontwarn com.airbnb.lottie.LottieAnimationView
-dontwarn com.airbnb.lottie.LottieProperty
-dontwarn com.airbnb.lottie.model.KeyPath
-dontwarn com.airbnb.lottie.value.LottieFrameInfo
-dontwarn com.airbnb.lottie.value.SimpleLottieValueCallback
```

or by adding the following dependency:

`    implementation 'com.airbnb.android:lottie:6.3.0'
`

Is the latter the way to proceed?

# Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Compile with release-2.11.1 

## Context 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating Version:
* SDK version: release-2.11.1

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by CheZhongSdk** [comment]
Hi @planetcoops, Thanks for reaching out! We tested our example apps, but couldn't reproduce the issue you reported. Zettle SDK should not force you to import Lottie library. Did the previous SDK version 2.6.7 work for you?

**Comment by planetcoops** [comment]
Yes, the previous SDK 2.6.7 was fine.

**Comment by planetcoops** [comment]
Has Lottie had been used to add animations for the "New UI style inspired by PayPal" in this release in the `com.izettle.ui.components.movie.OttoMovie `class?  OttoMovie has a field `com.izettle.ui.components.movie.OttoMovie.lottieAnimationView` .

Do I add proguard `-dontwarn` to suppress or add the Lottie dependency?

**Comment by CheZhongSdk** [comment]
SDK doesn't use `OttoMovie`, so it's safe to add -dontwarn to suppress it. We will fix this in the next SDK release. Thank you for your feedback!

**Comment by planetcoops** [comment]
Thank you for the clarification.
