### ISSUE TITLE
Zettle Card Reader Pairing Problem

### ISSUE THREAD

**Issue by E-MRE** [iZettle/sdk-android#99]
# Expected Behavior

Pairing successfully with card reader device and sale items.

# Current Behavior

Kiosk device find card reader, comes pairing code and it confirms but then application goes down. When I try with mobile device, it can pairing and sale successfully. These two android devices have same android version (android 11).

# Steps to Reproduce

Open app
initialize zettle sdk (android)
login via zettle account
try to sale using unpaired card reader device.
it happen after pairing devices.

## Context 

We recently purchased a card reader to process transactions with Zettle at a store in the UK. Our goal is to process sales through our own application using the SDK. We have successfully managed the entire process in the test environment. However, when we attempted to start live testing, we encountered an issue.

Specifically, we are unable to pair our Android device with the Zettle card reader we purchased. During the pairing process, we accept the confirmation code, but the SDK forces the application to close. No error message or warning is displayed. We have successfully paired the card reader with our mobile device and have processed sales, but the application closes during the pairing phase on the Kiosk device.

* Operating Version: android 11
* SDK version: 2.16.1

## Failure Logs

there is no log.

Video at the attachments.

https://github.com/user-attachments/assets/f8f21227-bc67-440e-b8d2-12607baea2cd

**Comment by fparmak** [comment]
Hi @E-MRE,
From video it looks like app is crashing. It would be great if you can somehow provide logs. It is really hard to guess what's wrong without it.
Also if same app is not crashing in another device, it may indicate something is not working ok on OS level. For example `Android Keystore`:
https://developer.android.com/privacy-and-security/keystore

**Comment by E-MRE** [comment]
Hello @fparmak 

I was thinking like you but app not crashing. Because I have a file logger and I use this system with Flutter.onError method. After this error occurred I checked the log file but there wasn't any log in the file.

Also kiosk and another device has same android version (android 11).

By the way I also try connect zettle card reader via example project of iZettle sdk [(example project)](https://github.com/iZettle/sdk-android/tree/master/Examples/Example-Kotlin) but it was the same result.

![WhatsApp Image 2024-08-30 at 12 29 25](https://github.com/user-attachments/assets/eb2486d0-1f37-46a8-9a97-739175a5abe2)

**Comment by fparmak** [comment]
Hi @E-MRE,
Is it possible to get a bug report?
https://developer.android.com/studio/debug/bug-report

**Comment by fparmak** [comment]
Hi @E-MRE,
Thank you for the bug report. Seems like same issue with this one:
https://github.com/iZettle/sdk-android/issues/85
And unfortunately this crash is coming from OS and we don't have fix for this. We see this it happens mostly on Android 11. So you can try to upgrade Android version.
